#cerad_tourn:
#    resource: "@CeradTournBundle/Resources/config/routing.yml"
#    prefix:   /

cerad_app__index:
  pattern:  /
  defaults: 
    _controller: cerad_app__index_controller:action
    _redirectWelcome: cerad_app__welcome
    _redirectHome:    cerad_app__home
      
cerad_app__welcome:
  pattern:  /welcome
  defaults: 
    _controller: cerad_app__welcome_controller:action
    _template: '@CeradApp/Welcome/WelcomePage.html.twig'
    _project:  '%cerad_project_project_default%'

